GET http://localhost:3001/api/tea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGFpc3kiLCJpYXQiOjE2NTUyMzc1MjJ9.fhgNv8IEgjOika_Lh1dC0WykkdJ7TJuLoeHa0GuG-_k

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "Daisy"
}